#pragma once 
#include "./include/k2c_tensor_include.h" 
void resnetv1(k2c_tensor* input_1_input, k2c_tensor* dense_output,float* conv2d_output_array,float* conv2d_padded_input_array,float* conv2d_kernel_array,float* conv2d_bias_array,float* batch_normalization_output_array,float* batch_normalization_mean_array,float* batch_normalization_stdev_array,float* batch_normalization_gamma_array,float* batch_normalization_beta_array,float* conv2d_1_output_array,float* conv2d_1_padded_input_array,float* conv2d_1_kernel_array,float* conv2d_1_bias_array,float* batch_normalization_1_output_array,float* batch_normalization_1_mean_array,float* batch_normalization_1_stdev_array,float* batch_normalization_1_gamma_array,float* batch_normalization_1_beta_array,float* conv2d_2_output_array,float* conv2d_2_padded_input_array,float* conv2d_2_kernel_array,float* conv2d_2_bias_array,float* batch_normalization_2_output_array,float* batch_normalization_2_mean_array,float* batch_normalization_2_stdev_array,float* batch_normalization_2_gamma_array,float* batch_normalization_2_beta_array,float* add_output_array,float* conv2d_3_output_array,float* conv2d_3_padded_input_array,float* conv2d_3_kernel_array,float* conv2d_3_bias_array,float* batch_normalization_3_output_array,float* batch_normalization_3_mean_array,float* batch_normalization_3_stdev_array,float* batch_normalization_3_gamma_array,float* batch_normalization_3_beta_array,float* conv2d_4_output_array,float* conv2d_4_padded_input_array,float* conv2d_4_kernel_array,float* conv2d_4_bias_array,float* conv2d_5_output_array,float* conv2d_5_padded_input_array,float* conv2d_5_kernel_array,float* conv2d_5_bias_array,float* batch_normalization_4_output_array,float* batch_normalization_4_mean_array,float* batch_normalization_4_stdev_array,float* batch_normalization_4_gamma_array,float* batch_normalization_4_beta_array,float* add_1_output_array,float* conv2d_6_output_array,float* conv2d_6_padded_input_array,float* conv2d_6_kernel_array,float* conv2d_6_bias_array,float* batch_normalization_5_output_array,float* batch_normalization_5_mean_array,float* batch_normalization_5_stdev_array,float* batch_normalization_5_gamma_array,float* batch_normalization_5_beta_array,float* conv2d_7_output_array,float* conv2d_7_padded_input_array,float* conv2d_7_kernel_array,float* conv2d_7_bias_array,float* conv2d_8_output_array,float* conv2d_8_padded_input_array,float* conv2d_8_kernel_array,float* conv2d_8_bias_array,float* batch_normalization_6_output_array,float* batch_normalization_6_mean_array,float* batch_normalization_6_stdev_array,float* batch_normalization_6_gamma_array,float* batch_normalization_6_beta_array,float* add_2_output_array,float* average_pooling2d_output_array,float* flatten_output_array,float* dense_kernel_array,float* dense_bias_array); 
void resnetv1_initialize(float** conv2d_output_array 
,float** conv2d_padded_input_array 
,float** conv2d_kernel_array 
,float** conv2d_bias_array 
,float** batch_normalization_output_array 
,float** batch_normalization_mean_array 
,float** batch_normalization_stdev_array 
,float** batch_normalization_gamma_array 
,float** batch_normalization_beta_array 
,float** conv2d_1_output_array 
,float** conv2d_1_padded_input_array 
,float** conv2d_1_kernel_array 
,float** conv2d_1_bias_array 
,float** batch_normalization_1_output_array 
,float** batch_normalization_1_mean_array 
,float** batch_normalization_1_stdev_array 
,float** batch_normalization_1_gamma_array 
,float** batch_normalization_1_beta_array 
,float** conv2d_2_output_array 
,float** conv2d_2_padded_input_array 
,float** conv2d_2_kernel_array 
,float** conv2d_2_bias_array 
,float** batch_normalization_2_output_array 
,float** batch_normalization_2_mean_array 
,float** batch_normalization_2_stdev_array 
,float** batch_normalization_2_gamma_array 
,float** batch_normalization_2_beta_array 
,float** add_output_array 
,float** conv2d_3_output_array 
,float** conv2d_3_padded_input_array 
,float** conv2d_3_kernel_array 
,float** conv2d_3_bias_array 
,float** batch_normalization_3_output_array 
,float** batch_normalization_3_mean_array 
,float** batch_normalization_3_stdev_array 
,float** batch_normalization_3_gamma_array 
,float** batch_normalization_3_beta_array 
,float** conv2d_4_output_array 
,float** conv2d_4_padded_input_array 
,float** conv2d_4_kernel_array 
,float** conv2d_4_bias_array 
,float** conv2d_5_output_array 
,float** conv2d_5_padded_input_array 
,float** conv2d_5_kernel_array 
,float** conv2d_5_bias_array 
,float** batch_normalization_4_output_array 
,float** batch_normalization_4_mean_array 
,float** batch_normalization_4_stdev_array 
,float** batch_normalization_4_gamma_array 
,float** batch_normalization_4_beta_array 
,float** add_1_output_array 
,float** conv2d_6_output_array 
,float** conv2d_6_padded_input_array 
,float** conv2d_6_kernel_array 
,float** conv2d_6_bias_array 
,float** batch_normalization_5_output_array 
,float** batch_normalization_5_mean_array 
,float** batch_normalization_5_stdev_array 
,float** batch_normalization_5_gamma_array 
,float** batch_normalization_5_beta_array 
,float** conv2d_7_output_array 
,float** conv2d_7_padded_input_array 
,float** conv2d_7_kernel_array 
,float** conv2d_7_bias_array 
,float** conv2d_8_output_array 
,float** conv2d_8_padded_input_array 
,float** conv2d_8_kernel_array 
,float** conv2d_8_bias_array 
,float** batch_normalization_6_output_array 
,float** batch_normalization_6_mean_array 
,float** batch_normalization_6_stdev_array 
,float** batch_normalization_6_gamma_array 
,float** batch_normalization_6_beta_array 
,float** add_2_output_array 
,float** average_pooling2d_output_array 
,float** flatten_output_array 
,float** dense_kernel_array 
,float** dense_bias_array 
); 
void resnetv1_terminate(float* conv2d_output_array,float* conv2d_padded_input_array,float* conv2d_kernel_array,float* conv2d_bias_array,float* batch_normalization_output_array,float* batch_normalization_mean_array,float* batch_normalization_stdev_array,float* batch_normalization_gamma_array,float* batch_normalization_beta_array,float* conv2d_1_output_array,float* conv2d_1_padded_input_array,float* conv2d_1_kernel_array,float* conv2d_1_bias_array,float* batch_normalization_1_output_array,float* batch_normalization_1_mean_array,float* batch_normalization_1_stdev_array,float* batch_normalization_1_gamma_array,float* batch_normalization_1_beta_array,float* conv2d_2_output_array,float* conv2d_2_padded_input_array,float* conv2d_2_kernel_array,float* conv2d_2_bias_array,float* batch_normalization_2_output_array,float* batch_normalization_2_mean_array,float* batch_normalization_2_stdev_array,float* batch_normalization_2_gamma_array,float* batch_normalization_2_beta_array,float* add_output_array,float* conv2d_3_output_array,float* conv2d_3_padded_input_array,float* conv2d_3_kernel_array,float* conv2d_3_bias_array,float* batch_normalization_3_output_array,float* batch_normalization_3_mean_array,float* batch_normalization_3_stdev_array,float* batch_normalization_3_gamma_array,float* batch_normalization_3_beta_array,float* conv2d_4_output_array,float* conv2d_4_padded_input_array,float* conv2d_4_kernel_array,float* conv2d_4_bias_array,float* conv2d_5_output_array,float* conv2d_5_padded_input_array,float* conv2d_5_kernel_array,float* conv2d_5_bias_array,float* batch_normalization_4_output_array,float* batch_normalization_4_mean_array,float* batch_normalization_4_stdev_array,float* batch_normalization_4_gamma_array,float* batch_normalization_4_beta_array,float* add_1_output_array,float* conv2d_6_output_array,float* conv2d_6_padded_input_array,float* conv2d_6_kernel_array,float* conv2d_6_bias_array,float* batch_normalization_5_output_array,float* batch_normalization_5_mean_array,float* batch_normalization_5_stdev_array,float* batch_normalization_5_gamma_array,float* batch_normalization_5_beta_array,float* conv2d_7_output_array,float* conv2d_7_padded_input_array,float* conv2d_7_kernel_array,float* conv2d_7_bias_array,float* conv2d_8_output_array,float* conv2d_8_padded_input_array,float* conv2d_8_kernel_array,float* conv2d_8_bias_array,float* batch_normalization_6_output_array,float* batch_normalization_6_mean_array,float* batch_normalization_6_stdev_array,float* batch_normalization_6_gamma_array,float* batch_normalization_6_beta_array,float* add_2_output_array,float* average_pooling2d_output_array,float* flatten_output_array,float* dense_kernel_array,float* dense_bias_array); 
